export const PAYMENTS_STRIPE_API_VERSION = '2025-01-27.acacia';
export const PAYMENTS_STRIPE_CURRENCY = 'usd';

export const ORDERS_CLIENT_GRPC_PROVIDER_TOKEN = Symbol(
  'ORDERS_CLIENT_GRPC_PROVIDER_TOKEN',
);
export const ORDERS_SERVICE_PROVIDER_TOKEN = Symbol(
  'ORDERS_SERVICE_PROVIDER_TOKEN',
);
