// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export const OrderStatus = { WAITING_FOR_PAYMENT: "WAITING_FOR_PAYMENT", COMPLETED: "COMPLETED" } as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];

export namespace OrderStatus {
  export type WAITING_FOR_PAYMENT = typeof OrderStatus.WAITING_FOR_PAYMENT;
  export type COMPLETED = typeof OrderStatus.COMPLETED;
}

export interface CreateOrderRequest {
  userId: string;
}

export interface GetOrderRequest {
  orderId: string;
}

export interface GetOrdersRequest {
  userId: string;
}

export interface GetOrderByIntentIdRequest {
  intentId: string;
}

export interface OrdersResponse {
  orders: OrderResponse[];
}

export interface OrderItemResponse {
  productId: string;
  quantity: number;
  price: number;
}

export interface OrderResponse {
  id: string;
  status: OrderStatus;
  userId: string;
  intentId: string;
  createdAt: Date;
  items: OrderItemResponse[];
}

export const ORDER_PACKAGE_NAME = "order";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<OrderResponse>;

  getOrder(request: GetOrderRequest): Observable<OrderResponse>;

  getOrderByIntentId(request: GetOrderByIntentIdRequest): Observable<OrderResponse>;

  getOrders(request: GetOrdersRequest): Observable<OrdersResponse>;
}

export interface OrderServiceController {
  createOrder(request: CreateOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrder(request: GetOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderByIntentId(
    request: GetOrderByIntentIdRequest,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrders(request: GetOrdersRequest): Promise<OrdersResponse> | Observable<OrdersResponse> | OrdersResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrder", "getOrderByIntentId", "getOrders"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
