// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export const PaymentStatus = {
  canceled: "canceled",
  processing: "processing",
  requires_action: "requires_action",
  requires_capture: "requires_capture",
  requires_confirmation: "requires_confirmation",
  requires_payment_method: "requires_payment_method",
  succeeded: "succeeded",
} as const;

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

export namespace PaymentStatus {
  export type canceled = typeof PaymentStatus.canceled;
  export type processing = typeof PaymentStatus.processing;
  export type requires_action = typeof PaymentStatus.requires_action;
  export type requires_capture = typeof PaymentStatus.requires_capture;
  export type requires_confirmation = typeof PaymentStatus.requires_confirmation;
  export type requires_payment_method = typeof PaymentStatus.requires_payment_method;
  export type succeeded = typeof PaymentStatus.succeeded;
}

export interface CreateIntentRequest {
  amountInCent: number;
}

export interface GetIntentRequest {
  intentId: string;
}

export interface IntentResponse {
  id: string;
  amount: number;
  currency: string;
  clientSecret: string;
  status: PaymentStatus;
}

export const PAYMENT_CURRENT_PACKAGE = "payment";

export interface PaymentServiceClient {
  createIntent(request: CreateIntentRequest): Observable<IntentResponse>;

  getIntent(request: GetIntentRequest): Observable<IntentResponse>;
}

export interface PaymentServiceController {
  createIntent(request: CreateIntentRequest): Promise<IntentResponse> | Observable<IntentResponse> | IntentResponse;

  getIntent(request: GetIntentRequest): Promise<IntentResponse> | Observable<IntentResponse> | IntentResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createIntent", "getIntent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
