// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: products.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp.pb";

export const protobufPackage = "products";

export enum ProductSortDirection {
  ASC = 0,
  DESC = 1,
}

export enum ProductSortBy {
  CREATED_AT = 0,
  RATING = 1,
  PRICE = 2,
}

export interface Category {
  id: number;
  name: string;
}

export interface Brand {
  id: number;
  name: string;
}

export interface Product {
  id: number;
  amount: number;
  currency: string;
  image: string;
  price: number;
  rating: number;
  title: string;
  createdAt: Timestamp | null;
  brand: Brand | null;
  category: Category | null;
}

export interface Image {
  buffer: Uint8Array;
  size: number;
  mimetype: string;
  encoding: string;
}

export interface CreateProductRequest {
  amount: number;
  brandId: number;
  categoryId: number;
  currency: number;
  image: Image | null;
  price: number;
  title: string;
}

export interface GetProductByIdRequest {
  id: number;
}

export interface ProductSort {
  direction: ProductSortDirection;
  by: ProductSortBy;
}

export interface GetProductsByFilterRequest {
  categoryId?: number | null | undefined;
  brandId?: number | null | undefined;
  sort?: ProductSort | null | undefined;
}

export const PRODUCTS_PACKAGE_NAME = "products";

export interface ProductsServiceClient {
  createProduct(request: CreateProductRequest, metadata?: Metadata): Observable<Product>;

  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Observable<Product>;

  getProductsByFilter(request: GetProductsByFilterRequest, metadata?: Metadata): Observable<Product>;
}

export interface ProductsServiceController {
  createProduct(request: CreateProductRequest, metadata?: Metadata): Promise<Product> | Observable<Product> | Product;

  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Promise<Product> | Observable<Product> | Product;

  getProductsByFilter(request: GetProductsByFilterRequest, metadata?: Metadata): Observable<Product>;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createProduct", "getProductById", "getProductsByFilter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "ProductsService";
