// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface CategoryResponse {
  id: string;
  slug: string;
  name: string;
}

export interface BrandResponse {
  id: string;
  slug: string;
  name: string;
}

export interface ProductResponse {
  id: string;
  amount: number;
  image: string;
  price: number;
  title: string;
  slug: string;
  description: string;
  rating?: number | null | undefined;
  createdAt: Date;
  brand: BrandResponse;
  category: CategoryResponse;
}

export interface GetProductByIdRequest {
  id: string;
}

export interface GetProductBySlugRequest {
  slug: string;
}

export interface GetCategoryBySlugRequest {
  slug: string;
}

export interface GetBrandBySlugRequest {
  slug: string;
}

export interface GetProductsByIdsRequest {
  ids: string[];
}

export interface GetProductsPaginationRequest {
  page: number;
  limit: number;
}

export interface GetFeaturedProductsRequest {
  pagination: GetProductsPaginationRequest;
}

export interface GetProductsByFilterRequest {
  brandSlug?: string | null | undefined;
  categorySlug?: string | null | undefined;
  pagination: GetProductsPaginationRequest;
}

export interface PaginationResponse {
  page: number;
  limit: number;
  totalCount: number;
}

export interface ProductsResponse {
  products: ProductResponse[];
  pagination: PaginationResponse;
}

export const PRODUCT_CURRENT_PACKAGE = "product";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface ProductServiceClient {
  getProductBySlug(request: GetProductBySlugRequest): Observable<ProductResponse>;

  getProductById(request: GetProductByIdRequest): Observable<ProductResponse>;

  getProductsByIds(request: GetProductsByIdsRequest): Observable<ProductResponse>;

  getProductsByFilter(request: GetProductsByFilterRequest): Observable<ProductsResponse>;

  getFeaturedProducts(request: GetFeaturedProductsRequest): Observable<ProductsResponse>;

  getCategoryBySlug(request: GetCategoryBySlugRequest): Observable<CategoryResponse>;

  getBrandBySlug(request: GetBrandBySlugRequest): Observable<BrandResponse>;
}

export interface ProductServiceController {
  getProductBySlug(
    request: GetProductBySlugRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  getProductById(
    request: GetProductByIdRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  getProductsByIds(request: GetProductsByIdsRequest): Observable<ProductResponse>;

  getProductsByFilter(
    request: GetProductsByFilterRequest,
  ): Promise<ProductsResponse> | Observable<ProductsResponse> | ProductsResponse;

  getFeaturedProducts(
    request: GetFeaturedProductsRequest,
  ): Promise<ProductsResponse> | Observable<ProductsResponse> | ProductsResponse;

  getCategoryBySlug(
    request: GetCategoryBySlugRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  getBrandBySlug(request: GetBrandBySlugRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getProductBySlug",
      "getProductById",
      "getProductsByIds",
      "getProductsByFilter",
      "getFeaturedProducts",
      "getCategoryBySlug",
      "getBrandBySlug",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
