// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp.pb";

export enum ProductSortDirection {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export enum ProductSortBy {
  CREATED_AT = 0,
  RATING = 1,
  PRICE = 2,
  UNRECOGNIZED = -1,
}

export interface Category {
  id: number;
  name: string;
}

export interface Brand {
  id: number;
  name: string;
}

export interface Product {
  id: number;
  amount: number;
  currency: string;
  image: string;
  price: number;
  title: string;
  rating?: number | undefined;
  createdAt: Timestamp | undefined;
  brand: Brand | undefined;
  category: Category | undefined;
}

export interface Image {
  buffer: Uint8Array;
  size: number;
  mimetype: string;
  encoding: string;
}

export interface CreateProductRequest {
  amount: number;
  brandId: number;
  categoryId: number;
  currency: number;
  price: number;
  title: string;
  image: Image | undefined;
}

export interface GetProductByIdRequest {
  id: number;
}

export interface ProductSort {
  direction: ProductSortDirection;
  by: ProductSortBy;
}

export interface GetProductsByFilterRequest {
  categoryId?: number | undefined;
  brandId?: number | undefined;
  sort?: ProductSort | undefined;
}

export interface UpdateProductRequest {
  id: number;
  amount?: number | undefined;
  currency?: string | undefined;
  image?: string | undefined;
  price?: number | undefined;
  rating?: number | undefined;
  title?: string | undefined;
}

export interface ProductsServiceClient {
  /** rpc CreateProduct(CreateProductRequest) returns (Product); */

  getProductById(request: GetProductByIdRequest): Observable<Product>;

  /** rpc UpdateProduct(UpdateProductRequest) returns (Product); */

  getProductsByFilter(request: GetProductsByFilterRequest): Observable<Product>;
}

export interface ProductsServiceController {
  /** rpc CreateProduct(CreateProductRequest) returns (Product); */

  getProductById(request: GetProductByIdRequest): Promise<Product> | Observable<Product> | Product;

  /** rpc UpdateProduct(UpdateProductRequest) returns (Product); */

  getProductsByFilter(request: GetProductsByFilterRequest): Observable<Product>;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProductById", "getProductsByFilter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "ProductsService";
