// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export interface User {
  id: number;
  name: string;
  email: string;
}

export interface CreateUserRequest {
  name: string;
  email: string;
  password: string;
}

export interface UpdateUserRequest {
  id: number;
  name?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
}

export interface DeleteUserRequest {
  id: number;
}

export interface GetUserByIdRequest {
  id: number;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface GetUserByCredentialsRequest {
  email: string;
  password: string;
}

export interface GetUsersRequest {
  page: number;
  pageSize: number;
}

export interface UsersServiceClient {
  createUser(request: CreateUserRequest): Observable<User>;

  getUserById(request: GetUserByIdRequest): Observable<User>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<User>;

  getUserByCredentials(request: GetUserByCredentialsRequest): Observable<User>;

  updateUser(request: UpdateUserRequest): Observable<User>;

  deleteUser(request: DeleteUserRequest): Observable<Empty>;

  getUsers(request: GetUsersRequest): Observable<User>;
}

export interface UsersServiceController {
  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;

  getUserById(request: GetUserByIdRequest): Promise<User> | Observable<User> | User;

  getUserByEmail(request: GetUserByEmailRequest): Promise<User> | Observable<User> | User;

  getUserByCredentials(request: GetUserByCredentialsRequest): Promise<User> | Observable<User> | User;

  updateUser(request: UpdateUserRequest): Promise<User> | Observable<User> | User;

  deleteUser(request: DeleteUserRequest): void;

  getUsers(request: GetUsersRequest): Observable<User>;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "getUserById",
      "getUserByEmail",
      "getUserByCredentials",
      "updateUser",
      "deleteUser",
      "getUsers",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
