name: ecommerce-api-keploy

services:
  api-gateway-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: api-gateway
    environment:
      GRPC_SERVICE_URL_USER: "user-service:50051"
      GRPC_SERVICE_URL_PRODUCT: "product-service:50051"
      GRPC_SERVICE_URL_CART: "cart-service:50051"
      GRPC_SERVICE_URL_ORDER: "order-service:50051"
      GRPC_SERVICE_URL_PAYMENT: "payment-service:50051"
      JWT_SECRET: "23cd6855c0ff0a1718f875458f8904b2b7a1b72b8066a75acaf6d6820397c2a3"
      SWAGGER_PATH: "/"
      SWAGGER_JSON_DOCUMENT_URL: "/document.json"
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service

  cart-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: cart-service
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-service:5432/cart-service"
      GRPC_SERVICE_URL_PRODUCT: "product-service:50051"
      GRPC_SERVICE_URL_CART: "0.0.0.0:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service

  notification-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: notification-service
    environment:
      MAIL_ADMIN_EMAIL: "admin@admin.com"
      MAIL_ADMIN_NAME: "admin"
      MAIL_SERVER_URL: "smtp://admin@admin.com:pass@smtp-service:1025"
      GRPC_SERVICE_URL_USER: "user-service:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service

  order-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: order-service
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-service:5432/order-service"
      GRPC_SERVICE_URL_CART: "cart-service:50051"
      GRPC_SERVICE_URL_ORDER: "0.0.0.0:50051"
      GRPC_SERVICE_URL_PAYMENT: "payment-service:50051"
      GRPC_SERVICE_URL_USER: "user-service:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service

  payment-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: payment-service
    environment:
      GRPC_SERVICE_URL_ORDER: "order-service:50051"
      GRPC_SERVICE_URL_PAYMENT: "0.0.0.0:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
      STRIPE_SECRET_KEY: ""
      STRIPE_WEBHOOK_WHSEC: ""
      PORT: 4242
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service

  product-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: product-service
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-service:5432/product-service"
      GRPC_SERVICE_URL_PRODUCT: "0.0.0.0:50051"
      GRPC_SERVICE_URL_ORDER: "order-service:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service

  user-service:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        APP_DIR: user-service
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-service:5432/user-service"
      GRPC_SERVICE_URL_USER: "0.0.0.0:50051"
      MQTT_URL: "mqtt://mqtt-service:1883"
    depends_on:
      - db-service
      - mqtt-service
      - smtp-service


