volumes:
  db-dev-data:

services:
  db-service:
    ports:
      - 5432:5432
    volumes:
      - db-dev-data:/var/lib/postgresql/data
  mqtt-service:
    ports:
      - 1883:1883
  smtp-service:
    ports:
      - 8025:8025
      - 1025:1025



