volumes:
  db-data:

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ./infra/mosquitto.conf:/mosquitto/config/mosquitto.conf


