volumes:
  db-data:

services:
  db-service:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  mqtt-service:
    image: eclipse-mosquitto:2
    volumes:
      - ./infra/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
  smtp-service:
    image: axllent/mailpit:v1.22
    restart: always
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 0
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_AUTH: "admin@admin.com:pass"



