// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: carts.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Product } from "./products";

export const protobufPackage = "carts";

export interface Cart {
  items: CartItem[];
  totalPrice: number;
}

export interface CartItem {
  quantity: number;
  product: Product | null;
}

export interface GetCartByUserIdRequest {
  userId: number;
}

export interface GetCartQuantityByUserIdRequest {
  userId: number;
}

export interface GetCartQuantityResponse {
  quantity: number;
}

export interface AddProductToCartRequest {
  productId: number;
  quantity: number;
  userId: number;
}

export const CARTS_PACKAGE_NAME = "carts";

export interface CartsServiceClient {
  addProductToCart(request: AddProductToCartRequest, metadata?: Metadata): Observable<GetCartQuantityResponse>;

  getCartByUserId(request: GetCartByUserIdRequest, metadata?: Metadata): Observable<Cart>;

  getCartQuantityByUserId(
    request: GetCartQuantityByUserIdRequest,
    metadata?: Metadata,
  ): Observable<GetCartQuantityResponse>;
}

export interface CartsServiceController {
  addProductToCart(
    request: AddProductToCartRequest,
    metadata?: Metadata,
  ): Promise<GetCartQuantityResponse> | Observable<GetCartQuantityResponse> | GetCartQuantityResponse;

  getCartByUserId(request: GetCartByUserIdRequest, metadata?: Metadata): Promise<Cart> | Observable<Cart> | Cart;

  getCartQuantityByUserId(
    request: GetCartQuantityByUserIdRequest,
    metadata?: Metadata,
  ): Promise<GetCartQuantityResponse> | Observable<GetCartQuantityResponse> | GetCartQuantityResponse;
}

export function CartsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addProductToCart", "getCartByUserId", "getCartQuantityByUserId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CARTS_SERVICE_NAME = "CartsService";
