// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: carts.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "carts";

export interface CartItemResponse {
  quantity: number;
  productId: number;
  price: number;
}

export interface CartResponse {
  items: CartItemResponse[];
  totalQuantity: number;
  totalPrice: number;
}

export interface GetCartRequest {
  userId: number;
}

export interface AddToCartRequest {
  productId: number;
  quantity: number;
  userId: number;
}

export interface RemoveFromCartRequest {
  userId: number;
  productId: number;
}

export interface RemoveCartRequest {
  userId: number;
}

export const CARTS_PACKAGE_NAME = "carts";

export interface CartsServiceClient {
  addToCart(request: AddToCartRequest): Observable<CartResponse>;

  getCart(request: GetCartRequest): Observable<CartResponse>;

  removeFromCart(request: RemoveFromCartRequest): Observable<CartResponse>;

  removeCart(request: RemoveCartRequest): Observable<Empty>;
}

export interface CartsServiceController {
  addToCart(request: AddToCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  getCart(request: GetCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  removeFromCart(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  removeCart(request: RemoveCartRequest): void;
}

export function CartsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addToCart", "getCart", "removeFromCart", "removeCart"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CARTS_SERVICE_NAME = "CartsService";
