// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: orders.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "orders";

export interface OrderResponse {
  id: number;
  status: string;
  userId: number;
  intentId: string;
  createdAt: Date | null;
  items: OrderItemResponse[];
}

export interface OrderItemResponse {
  productId: number;
  quantity: number;
  price: number;
}

export interface CreateOrderRequest {
  userId: number;
}

export interface GetOrderRequest {
  orderId: number;
}

export interface GetOrdersRequest {
  userId: number;
}

export interface GetOrdersResponse {
  orders: OrderResponse[];
}

export interface CompleteOrdersRequest {
  intentId: string;
}

export interface GetOrderByIntentIdRequest {
  intentId: string;
}

export const ORDERS_PACKAGE_NAME = "orders";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface OrdersServiceClient {
  createOrder(request: CreateOrderRequest): Observable<OrderResponse>;

  getOrder(request: GetOrderRequest): Observable<OrderResponse>;

  getOrderByIntentId(request: GetOrderByIntentIdRequest): Observable<OrderResponse>;

  getOrders(request: GetOrdersRequest): Observable<GetOrdersResponse>;

  completeOrder(request: CompleteOrdersRequest): Observable<Empty>;
}

export interface OrdersServiceController {
  createOrder(request: CreateOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrder(request: GetOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderByIntentId(
    request: GetOrderByIntentIdRequest,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrders(request: GetOrdersRequest): Promise<GetOrdersResponse> | Observable<GetOrdersResponse> | GetOrdersResponse;

  completeOrder(request: CompleteOrdersRequest): void;
}

export function OrdersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrder", "getOrderByIntentId", "getOrders", "completeOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrdersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrdersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDERS_SERVICE_NAME = "OrdersService";
