// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: payments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payments";

export interface CreateIntentRequest {
  amountInCent: number;
}

export interface CreateResponse {
  intentId: string;
}

export interface GetIntentRequest {
  intentId: string;
}

export interface GetIntentResponse {
  clientSecret: string;
  amount: number;
  status: string;
  currency: string;
}

export const PAYMENTS_PACKAGE_NAME = "payments";

export interface PaymentsServiceClient {
  createIntent(request: CreateIntentRequest): Observable<CreateResponse>;

  getIntent(request: GetIntentRequest): Observable<GetIntentResponse>;
}

export interface PaymentsServiceController {
  createIntent(request: CreateIntentRequest): Promise<CreateResponse> | Observable<CreateResponse> | CreateResponse;

  getIntent(request: GetIntentRequest): Promise<GetIntentResponse> | Observable<GetIntentResponse> | GetIntentResponse;
}

export function PaymentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createIntent", "getIntent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENTS_SERVICE_NAME = "PaymentsService";
