// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: payments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payments";

export const PaymentStatus = {
  canceled: "canceled",
  processing: "processing",
  requires_action: "requires_action",
  requires_capture: "requires_capture",
  requires_confirmation: "requires_confirmation",
  requires_payment_method: "requires_payment_method",
  succeeded: "succeeded",
} as const;

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

export namespace PaymentStatus {
  export type canceled = typeof PaymentStatus.canceled;
  export type processing = typeof PaymentStatus.processing;
  export type requires_action = typeof PaymentStatus.requires_action;
  export type requires_capture = typeof PaymentStatus.requires_capture;
  export type requires_confirmation = typeof PaymentStatus.requires_confirmation;
  export type requires_payment_method = typeof PaymentStatus.requires_payment_method;
  export type succeeded = typeof PaymentStatus.succeeded;
}

export interface CreateIntentRequest {
  amountInCent: number;
}

export interface CreateResponse {
  intentId: string;
}

export interface GetIntentRequest {
  intentId: string;
}

export interface GetIntentResponse {
  id: string;
  clientSecret: string;
  amount: number;
  status: PaymentStatus;
  currency: string;
}

export const PAYMENTS_PACKAGE_NAME = "payments";

export interface PaymentsServiceClient {
  createIntent(request: CreateIntentRequest): Observable<CreateResponse>;

  getIntent(request: GetIntentRequest): Observable<GetIntentResponse>;
}

export interface PaymentsServiceController {
  createIntent(request: CreateIntentRequest): Promise<CreateResponse> | Observable<CreateResponse> | CreateResponse;

  getIntent(request: GetIntentRequest): Promise<GetIntentResponse> | Observable<GetIntentResponse> | GetIntentResponse;
}

export function PaymentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createIntent", "getIntent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENTS_SERVICE_NAME = "PaymentsService";
