// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.0.0
//   protoc               v3.21.12
// source: products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { wrappers } from 'protobufjs';
import { Observable } from 'rxjs';

export const protobufPackage = 'products';

export interface Category {
  id: number;
  name: string;
}

export interface Brand {
  id: number;
  name: string;
}

export interface Product {
  id: number;
  amount: number;
  image: string;
  price: number;
  title: string;
  description: string;
  rating?: number | null | undefined;
  createdAt: Date;
  brand: Brand;
  category: Category;
}

export interface GetProductByIdRequest {
  id: number;
}

export interface GetProductsByIdsRequest {
  ids: number[];
}

export interface PaginationRequest {
  page: number;
  limit: number;
}

export interface GetFeaturedProductsRequest {
  pagination: PaginationRequest;
}

export interface GetProductsByFilterRequest {
  brandId?: number | null | undefined;
  categoryId?: number | null | undefined;
  pagination: PaginationRequest;
}

export interface PaginationResponse {
  page: number;
  limit: number;
  totalCount: number;
}

export interface ProductsResponse {
  products: Product[];
  pagination: PaginationResponse;
}

export interface ProductsByFilterResponse {
  products: Product[];
  pagination: PaginationResponse;
  brand?: Brand | null | undefined;
  category?: Category | null | undefined;
}

export const PRODUCTS_PACKAGE_NAME = 'products';

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return {
      seconds: value.getTime() / 1000,
      nanos: (value.getTime() % 1000) * 1e6,
    };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface ProductsServiceClient {
  getProductById(request: GetProductByIdRequest): Observable<Product>;

  getProductsByIds(request: GetProductsByIdsRequest): Observable<Product>;

  getProductsByFilter(
    request: GetProductsByFilterRequest,
  ): Observable<ProductsByFilterResponse>;

  getFeaturedProducts(
    request: GetFeaturedProductsRequest,
  ): Observable<ProductsResponse>;
}

export interface ProductsServiceController {
  getProductById(
    request: GetProductByIdRequest,
  ): Promise<Product> | Observable<Product> | Product;

  getProductsByIds(request: GetProductsByIdsRequest): Observable<Product>;

  getProductsByFilter(
    request: GetProductsByFilterRequest,
  ):
    | Promise<ProductsByFilterResponse>
    | Observable<ProductsByFilterResponse>
    | ProductsByFilterResponse;

  getFeaturedProducts(
    request: GetFeaturedProductsRequest,
  ):
    | Promise<ProductsResponse>
    | Observable<ProductsResponse>
    | ProductsResponse;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getProductById',
      'getProductsByIds',
      'getProductsByFilter',
      'getFeaturedProducts',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('ProductsService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('ProductsService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PRODUCTS_SERVICE_NAME = 'ProductsService';
