// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: products.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface Category {
  id: number;
  name: string;
}

export interface Brand {
  id: number;
  name: string;
}

export interface Product {
  id: number;
  amount: number;
  currency: string;
  image: string;
  price: number;
  title: string;
  description: string;
  rating?: number | null | undefined;
  createdAt: Date | null;
  brand: Brand | null;
  category: Category | null;
}

export interface GetProductByIdRequest {
  id: number;
}

export interface PaginationRequest {
  page: number;
  limit: number;
}

export interface GetFeaturedProductsRequest {
  pagination: PaginationRequest | null;
}

export interface GetProductsByFilterRequest {
  brandId?: number | null | undefined;
  categoryId?: number | null | undefined;
  pagination: PaginationRequest | null;
}

export interface PaginationResponse {
  page: number;
  limit: number;
  totalCount: number;
}

export interface ProductsResponse {
  products: Product[];
  pagination: PaginationResponse | null;
}

export interface ProductsByFilterResponse {
  products: Product[];
  pagination: PaginationResponse | null;
  brand?: Brand | null | undefined;
  category?: Category | null | undefined;
}

export const PRODUCTS_PACKAGE_NAME = "products";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface ProductsServiceClient {
  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Observable<Product>;

  getProductsByFilter(request: GetProductsByFilterRequest, metadata?: Metadata): Observable<ProductsByFilterResponse>;

  getFeaturedProducts(request: GetFeaturedProductsRequest, metadata?: Metadata): Observable<ProductsResponse>;
}

export interface ProductsServiceController {
  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Promise<Product> | Observable<Product> | Product;

  getProductsByFilter(
    request: GetProductsByFilterRequest,
    metadata?: Metadata,
  ): Promise<ProductsByFilterResponse> | Observable<ProductsByFilterResponse> | ProductsByFilterResponse;

  getFeaturedProducts(
    request: GetFeaturedProductsRequest,
    metadata?: Metadata,
  ): Promise<ProductsResponse> | Observable<ProductsResponse> | ProductsResponse;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProductById", "getProductsByFilter", "getFeaturedProducts"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "ProductsService";
