// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: products.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface Category {
  id: number;
  name: string;
}

export interface Brand {
  id: number;
  name: string;
}

export interface Product {
  id: number;
  amount: number;
  currency: string;
  image: string;
  price: number;
  title: string;
  rating?: number | null | undefined;
  createdAt: Date | null;
  brand: Brand | null;
  category: Category | null;
}

export interface Image {
  buffer: Uint8Array;
  size: number;
  mimetype: string;
  encoding: string;
}

export interface CreateProductRequest {
  amount: number;
  brandId: number;
  categoryId: number;
  currency: number;
  price: number;
  title: string;
  image: Image | null;
}

export interface GetProductByIdRequest {
  id: number;
}

export interface GetProductsByFilterRequest {
  categoryId?:
    | number
    | null
    | undefined;
  /**
   * optional ProductSortDirection sortDirection = 3;
   * optional ProductSortBy sortBy = 4;
   */
  brandId?: number | null | undefined;
}

export interface UpdateProductRequest {
  id: number;
  amount?: number | null | undefined;
  currency?: string | null | undefined;
  image?: string | null | undefined;
  price?: number | null | undefined;
  rating?: number | null | undefined;
  title?: string | null | undefined;
}

export const PRODUCTS_PACKAGE_NAME = "products";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface ProductsServiceClient {
  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Observable<Product>;

  getProductsByFilter(request: GetProductsByFilterRequest, metadata?: Metadata): Observable<Product>;
}

export interface ProductsServiceController {
  getProductById(request: GetProductByIdRequest, metadata?: Metadata): Promise<Product> | Observable<Product> | Product;

  getProductsByFilter(request: GetProductsByFilterRequest, metadata?: Metadata): Observable<Product>;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProductById", "getProductsByFilter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "ProductsService";
