// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";
import {
  type AuthControllerSignupData,
  type AuthControllerSignupError,
  type AuthControllerSignupResponse,
  type AuthControllerSigninData,
  type AuthControllerSigninError,
  type AuthControllerSigninResponse,
  type AuthControllerMeError,
  type AuthControllerMeResponse,
  type ProductsControllerGetFeaturedProductsData,
  type ProductsControllerGetFeaturedProductsError,
  type ProductsControllerGetFeaturedProductsResponse,
  type ProductsControllerGetProductBySlugData,
  type ProductsControllerGetProductBySlugError,
  type ProductsControllerGetProductBySlugResponse,
  type ProductsControllerGetProductsByFilterData,
  type ProductsControllerGetProductsByFilterError,
  type ProductsControllerGetProductsByFilterResponse,
  type CartsControllerGetCartError,
  type CartsControllerGetCartResponse,
  type CartsControllerAddToCartData,
  type CartsControllerAddToCartError,
  type CartsControllerAddToCartResponse,
  type CartsControllerRemoveFromCartData,
  type CartsControllerRemoveFromCartError,
  type CartsControllerRemoveFromCartResponse,
  type OrdersControllerGetOrdersError,
  type OrdersControllerGetOrdersResponse,
  type OrdersControllerAddOrderError,
  type OrdersControllerAddOrderResponse,
  type OrdersControllerGetOrderData,
  type OrdersControllerGetOrderError,
  type OrdersControllerGetOrderResponse,
  type OrdersControllerGetOrderIntentData,
  type OrdersControllerGetOrderIntentError,
  type OrdersControllerGetOrderIntentResponse,
  ProductsControllerGetFeaturedProductsResponseTransformer,
  ProductsControllerGetProductBySlugResponseTransformer,
  ProductsControllerGetProductsByFilterResponseTransformer,
  CartsControllerGetCartResponseTransformer,
  CartsControllerAddToCartResponseTransformer,
  CartsControllerRemoveFromCartResponseTransformer,
  OrdersControllerGetOrdersResponseTransformer,
  OrdersControllerAddOrderResponseTransformer,
  OrdersControllerGetOrderResponseTransformer,
  OrdersControllerGetOrderIntentResponseTransformer,
} from "./types.gen";

export const client = createClient(createConfig());

export const authControllerSignup = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthControllerSignupData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerSignupResponse,
    AuthControllerSignupError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/signup",
  });
};

export const authControllerSignin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthControllerSigninData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerSigninResponse,
    AuthControllerSigninError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/signin",
  });
};

export const authControllerMe = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    AuthControllerMeResponse,
    AuthControllerMeError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/me",
  });
};

export const productsControllerGetFeaturedProducts = <
  ThrowOnError extends boolean = false
>(
  options: OptionsLegacyParser<
    ProductsControllerGetFeaturedProductsData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetFeaturedProductsResponse,
    ProductsControllerGetFeaturedProductsError,
    ThrowOnError
  >({
    ...options,
    url: "/products/featured",
    responseTransformer:
      ProductsControllerGetFeaturedProductsResponseTransformer,
  });
};

export const productsControllerGetProductBySlug = <
  ThrowOnError extends boolean = false
>(
  options: OptionsLegacyParser<
    ProductsControllerGetProductBySlugData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductBySlugResponse,
    ProductsControllerGetProductBySlugError,
    ThrowOnError
  >({
    ...options,
    url: "/products/{slug}",
    responseTransformer: ProductsControllerGetProductBySlugResponseTransformer,
  });
};

export const productsControllerGetProductsByFilter = <
  ThrowOnError extends boolean = false
>(
  options: OptionsLegacyParser<
    ProductsControllerGetProductsByFilterData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductsByFilterResponse,
    ProductsControllerGetProductsByFilterError,
    ThrowOnError
  >({
    ...options,
    url: "/products",
    responseTransformer:
      ProductsControllerGetProductsByFilterResponseTransformer,
  });
};

export const cartsControllerGetCart = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    CartsControllerGetCartResponse,
    CartsControllerGetCartError,
    ThrowOnError
  >({
    ...options,
    url: "/cart",
    responseTransformer: CartsControllerGetCartResponseTransformer,
  });
};

export const cartsControllerAddToCart = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CartsControllerAddToCartData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CartsControllerAddToCartResponse,
    CartsControllerAddToCartError,
    ThrowOnError
  >({
    ...options,
    url: "/cart/product/{productId}",
    responseTransformer: CartsControllerAddToCartResponseTransformer,
  });
};

export const cartsControllerRemoveFromCart = <
  ThrowOnError extends boolean = false
>(
  options: OptionsLegacyParser<CartsControllerRemoveFromCartData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    CartsControllerRemoveFromCartResponse,
    CartsControllerRemoveFromCartError,
    ThrowOnError
  >({
    ...options,
    url: "/cart/product/{productId}",
    responseTransformer: CartsControllerRemoveFromCartResponseTransformer,
  });
};

export const ordersControllerGetOrders = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    OrdersControllerGetOrdersResponse,
    OrdersControllerGetOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/orders",
    responseTransformer: OrdersControllerGetOrdersResponseTransformer,
  });
};

export const ordersControllerAddOrder = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    OrdersControllerAddOrderResponse,
    OrdersControllerAddOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/orders",
    responseTransformer: OrdersControllerAddOrderResponseTransformer,
  });
};

export const ordersControllerGetOrder = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersControllerGetOrderData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    OrdersControllerGetOrderResponse,
    OrdersControllerGetOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/orders/{orderId}",
    responseTransformer: OrdersControllerGetOrderResponseTransformer,
  });
};

export const ordersControllerGetOrderIntent = <
  ThrowOnError extends boolean = false
>(
  options: OptionsLegacyParser<OrdersControllerGetOrderIntentData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    OrdersControllerGetOrderIntentResponse,
    OrdersControllerGetOrderIntentError,
    ThrowOnError
  >({
    ...options,
    url: "/orders/{orderId}/intent",
    responseTransformer: OrdersControllerGetOrderIntentResponseTransformer,
  });
};
