// This file is auto-generated by @hey-api/openapi-ts

export type AddToCartRequestDto = {
  quantity: number;
};

export type AuthorizedUserResponseDto = {
  id: string;
  name: string;
  email: string;
};

export type BrandResponseDto = {
  id: string;
  slug: string;
  name: string;
};

export type CartItemResponseDto = {
  productId: string;
  price: number;
  quantity: number;
  product: ProductResponseDto;
};

export type CartResponseDto = {
  totalPrice: number;
  totalQuantity: number;
  items: Array<CartItemResponseDto>;
};

export type CategoryResponseDto = {
  id: string;
  slug: string;
  name: string;
};

export type GetProductsPaginationRequestDto = {
  page: number;
  limit: number;
};

export type IntentResponseDto = {
  id: string;
  amount: number;
  status:
    | "canceled"
    | "processing"
    | "requires_action"
    | "requires_capture"
    | "requires_confirmation"
    | "requires_payment_method"
    | "succeeded";
  currency: string;
  clientSecret: string;
};

export type status =
  | "canceled"
  | "processing"
  | "requires_action"
  | "requires_capture"
  | "requires_confirmation"
  | "requires_payment_method"
  | "succeeded";

export type LoggedInResponseDto = {
  user: AuthorizedUserResponseDto;
  accessToken: string;
};

export type OrderIntentResponseDto = {
  id: string;
  userId: string;
  createdAt: Date;
  status: "WAITING_FOR_PAYMENT" | "COMPLETED";
  intentId: string;
  totalPrice: number;
  items: Array<OrderProductsItemResponseDto>;
  intent: IntentResponseDto;
};

export type status2 = "WAITING_FOR_PAYMENT" | "COMPLETED";

export type OrderItemResponseDto = {
  productId: string;
  quantity: number;
  price: number;
};

export type OrderProductsItemResponseDto = {
  productId: string;
  quantity: number;
  price: number;
  product: ProductResponseDto;
};

export type OrderProductsResponseDto = {
  id: string;
  userId: string;
  createdAt: Date;
  status: "WAITING_FOR_PAYMENT" | "COMPLETED";
  intentId: string;
  totalPrice: number;
  items: Array<OrderProductsItemResponseDto>;
};

export type OrderResponseDto = {
  id: string;
  userId: string;
  createdAt: Date;
  status: "WAITING_FOR_PAYMENT" | "COMPLETED";
  intentId: string;
  items: Array<OrderItemResponseDto>;
  totalPrice: number;
};

export type PaginationResponseDto = {
  page: number;
  limit: number;
  totalCount: number;
};

export type ProductResponseDto = {
  id: string;
  amount: number;
  image: string;
  price: number;
  title: string;
  slug: string;
  description: string;
  rating?: number | null;
  createdAt: Date;
  brand: BrandResponseDto;
  category: CategoryResponseDto;
};

export type ProductsByFilterResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
  brand: BrandResponseDto | null;
  category: CategoryResponseDto | null;
};

export type ProductsResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
};

export type RequestSigninDto = {
  email: string;
  password: string;
};

export type RequestSignupDto = {
  name: string;
  email: string;
  password: string;
};

export type AuthControllerSignupData = {
  body: RequestSignupDto;
};

export type AuthControllerSignupResponse = LoggedInResponseDto;

export type AuthControllerSignupError = unknown;

export type AuthControllerSigninData = {
  body: RequestSigninDto;
};

export type AuthControllerSigninResponse = LoggedInResponseDto;

export type AuthControllerSigninError = unknown;

export type AuthControllerMeResponse = AuthorizedUserResponseDto;

export type AuthControllerMeError = unknown;

export type ProductsControllerGetFeaturedProductsData = {
  query: {
    pagination: GetProductsPaginationRequestDto;
  };
};

export type ProductsControllerGetFeaturedProductsResponse = ProductsResponseDto;

export type ProductsControllerGetFeaturedProductsError = unknown;

export type ProductsControllerGetProductBySlugData = {
  path: {
    slug: string;
  };
};

export type ProductsControllerGetProductBySlugResponse = ProductResponseDto;

export type ProductsControllerGetProductBySlugError = unknown;

export type ProductsControllerGetProductsByFilterData = {
  query: {
    brandSlug?: string;
    categorySlug?: string;
    pagination: GetProductsPaginationRequestDto;
  };
};

export type ProductsControllerGetProductsByFilterResponse =
  ProductsByFilterResponseDto;

export type ProductsControllerGetProductsByFilterError = unknown;

export type CartsControllerGetCartResponse = CartResponseDto;

export type CartsControllerGetCartError = unknown;

export type CartsControllerAddToCartData = {
  body: AddToCartRequestDto;
  path: {
    productId: string;
  };
};

export type CartsControllerAddToCartResponse = CartResponseDto;

export type CartsControllerAddToCartError = unknown;

export type CartsControllerRemoveFromCartData = {
  path: {
    productId: string;
  };
};

export type CartsControllerRemoveFromCartResponse = CartResponseDto;

export type CartsControllerRemoveFromCartError = unknown;

export type OrdersControllerGetOrdersResponse = Array<OrderResponseDto>;

export type OrdersControllerGetOrdersError = unknown;

export type OrdersControllerAddOrderResponse = OrderResponseDto;

export type OrdersControllerAddOrderError = unknown;

export type OrdersControllerGetOrderData = {
  path: {
    orderId: string;
  };
};

export type OrdersControllerGetOrderResponse = OrderProductsResponseDto;

export type OrdersControllerGetOrderError = unknown;

export type OrdersControllerGetOrderIntentData = {
  path: {
    orderId: string;
  };
};

export type OrdersControllerGetOrderIntentResponse = OrderIntentResponseDto;

export type OrdersControllerGetOrderIntentError = unknown;

export type ProductsControllerGetFeaturedProductsResponseTransformer = (
  data: any
) => Promise<ProductsControllerGetFeaturedProductsResponse>;

export type ProductsResponseDtoModelResponseTransformer = (
  data: any
) => ProductsResponseDto;

export type ProductResponseDtoModelResponseTransformer = (
  data: any
) => ProductResponseDto;

export const ProductResponseDtoModelResponseTransformer: ProductResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    return data;
  };

export const ProductsResponseDtoModelResponseTransformer: ProductsResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.products)) {
      data.products.forEach(ProductResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const ProductsControllerGetFeaturedProductsResponseTransformer: ProductsControllerGetFeaturedProductsResponseTransformer =
  async (data) => {
    ProductsResponseDtoModelResponseTransformer(data);
    return data;
  };

export type ProductsControllerGetProductBySlugResponseTransformer = (
  data: any
) => Promise<ProductsControllerGetProductBySlugResponse>;

export const ProductsControllerGetProductBySlugResponseTransformer: ProductsControllerGetProductBySlugResponseTransformer =
  async (data) => {
    ProductResponseDtoModelResponseTransformer(data);
    return data;
  };

export type ProductsControllerGetProductsByFilterResponseTransformer = (
  data: any
) => Promise<ProductsControllerGetProductsByFilterResponse>;

export type ProductsByFilterResponseDtoModelResponseTransformer = (
  data: any
) => ProductsByFilterResponseDto;

export const ProductsByFilterResponseDtoModelResponseTransformer: ProductsByFilterResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.products)) {
      data.products.forEach(ProductResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const ProductsControllerGetProductsByFilterResponseTransformer: ProductsControllerGetProductsByFilterResponseTransformer =
  async (data) => {
    ProductsByFilterResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerGetCartResponseTransformer = (
  data: any
) => Promise<CartsControllerGetCartResponse>;

export type CartResponseDtoModelResponseTransformer = (
  data: any
) => CartResponseDto;

export type CartItemResponseDtoModelResponseTransformer = (
  data: any
) => CartItemResponseDto;

export const CartItemResponseDtoModelResponseTransformer: CartItemResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.product) {
      ProductResponseDtoModelResponseTransformer(data.product);
    }
    return data;
  };

export const CartResponseDtoModelResponseTransformer: CartResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.items)) {
      data.items.forEach(CartItemResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const CartsControllerGetCartResponseTransformer: CartsControllerGetCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerAddToCartResponseTransformer = (
  data: any
) => Promise<CartsControllerAddToCartResponse>;

export const CartsControllerAddToCartResponseTransformer: CartsControllerAddToCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerRemoveFromCartResponseTransformer = (
  data: any
) => Promise<CartsControllerRemoveFromCartResponse>;

export const CartsControllerRemoveFromCartResponseTransformer: CartsControllerRemoveFromCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type OrdersControllerGetOrdersResponseTransformer = (
  data: any
) => Promise<OrdersControllerGetOrdersResponse>;

export type OrderResponseDtoModelResponseTransformer = (
  data: any
) => OrderResponseDto;

export const OrderResponseDtoModelResponseTransformer: OrderResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    return data;
  };

export const OrdersControllerGetOrdersResponseTransformer: OrdersControllerGetOrdersResponseTransformer =
  async (data) => {
    if (Array.isArray(data)) {
      data.forEach(OrderResponseDtoModelResponseTransformer);
    }
    return data;
  };

export type OrdersControllerAddOrderResponseTransformer = (
  data: any
) => Promise<OrdersControllerAddOrderResponse>;

export const OrdersControllerAddOrderResponseTransformer: OrdersControllerAddOrderResponseTransformer =
  async (data) => {
    OrderResponseDtoModelResponseTransformer(data);
    return data;
  };

export type OrdersControllerGetOrderResponseTransformer = (
  data: any
) => Promise<OrdersControllerGetOrderResponse>;

export type OrderProductsResponseDtoModelResponseTransformer = (
  data: any
) => OrderProductsResponseDto;

export type OrderProductsItemResponseDtoModelResponseTransformer = (
  data: any
) => OrderProductsItemResponseDto;

export const OrderProductsItemResponseDtoModelResponseTransformer: OrderProductsItemResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.product) {
      ProductResponseDtoModelResponseTransformer(data.product);
    }
    return data;
  };

export const OrderProductsResponseDtoModelResponseTransformer: OrderProductsResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    if (Array.isArray(data?.items)) {
      data.items.forEach(OrderProductsItemResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const OrdersControllerGetOrderResponseTransformer: OrdersControllerGetOrderResponseTransformer =
  async (data) => {
    OrderProductsResponseDtoModelResponseTransformer(data);
    return data;
  };

export type OrdersControllerGetOrderIntentResponseTransformer = (
  data: any
) => Promise<OrdersControllerGetOrderIntentResponse>;

export type OrderIntentResponseDtoModelResponseTransformer = (
  data: any
) => OrderIntentResponseDto;

export const OrderIntentResponseDtoModelResponseTransformer: OrderIntentResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    if (Array.isArray(data?.items)) {
      data.items.forEach(OrderProductsItemResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const OrdersControllerGetOrderIntentResponseTransformer: OrdersControllerGetOrderIntentResponseTransformer =
  async (data) => {
    OrderIntentResponseDtoModelResponseTransformer(data);
    return data;
  };
