// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-fetch';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import {
  authControllerMe,
  authControllerSignin,
  authControllerSignup,
  cartsControllerAddToCart,
  cartsControllerGetCart,
  cartsControllerRemoveFromCart,
  client,
  ordersControllerCancelOrder,
  ordersControllerCreateOrder,
  ordersControllerGetOrder,
  ordersControllerGetOrderIntent,
  ordersControllerGetOrders,
  productsControllerGetFeaturedProducts,
  productsControllerGetProductBySlug,
  productsControllerGetProductsByFilter,
} from '../sdk.gen';
import type {
  AuthControllerSigninData,
  AuthControllerSigninError,
  AuthControllerSigninResponse,
  AuthControllerSignupData,
  AuthControllerSignupError,
  AuthControllerSignupResponse,
  CartsControllerAddToCartData,
  CartsControllerAddToCartError,
  CartsControllerAddToCartResponse,
  CartsControllerRemoveFromCartData,
  CartsControllerRemoveFromCartError,
  CartsControllerRemoveFromCartResponse,
  OrdersControllerCancelOrderData,
  OrdersControllerCancelOrderError,
  OrdersControllerCancelOrderResponse,
  OrdersControllerCreateOrderError,
  OrdersControllerCreateOrderResponse,
  OrdersControllerGetOrderData,
  OrdersControllerGetOrderIntentData,
  ProductsControllerGetFeaturedProductsData,
  ProductsControllerGetProductBySlugData,
  ProductsControllerGetProductsByFilterData,
} from '../types.gen';

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const authControllerSignupQueryKey = (
  options: OptionsLegacyParser<AuthControllerSignupData>,
) => [createQueryKey('authControllerSignup', options)];

export const authControllerSignupOptions = (
  options: OptionsLegacyParser<AuthControllerSignupData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerSignup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerSignupQueryKey(options),
  });
};

export const authControllerSignupMutation = (
  options?: Partial<OptionsLegacyParser<AuthControllerSignupData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AuthControllerSignupResponse,
    AuthControllerSignupError,
    OptionsLegacyParser<AuthControllerSignupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await authControllerSignup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authControllerSigninQueryKey = (
  options: OptionsLegacyParser<AuthControllerSigninData>,
) => [createQueryKey('authControllerSignin', options)];

export const authControllerSigninOptions = (
  options: OptionsLegacyParser<AuthControllerSigninData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerSignin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerSigninQueryKey(options),
  });
};

export const authControllerSigninMutation = (
  options?: Partial<OptionsLegacyParser<AuthControllerSigninData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AuthControllerSigninResponse,
    AuthControllerSigninError,
    OptionsLegacyParser<AuthControllerSigninData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await authControllerSignin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authControllerMeQueryKey = (options?: OptionsLegacyParser) => [
  createQueryKey('authControllerMe', options),
];

export const authControllerMeOptions = (options?: OptionsLegacyParser) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerMeQueryKey(options),
  });
};

export const productsControllerGetFeaturedProductsQueryKey = (
  options: OptionsLegacyParser<ProductsControllerGetFeaturedProductsData>,
) => [createQueryKey('productsControllerGetFeaturedProducts', options)];

export const productsControllerGetFeaturedProductsOptions = (
  options: OptionsLegacyParser<ProductsControllerGetFeaturedProductsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await productsControllerGetFeaturedProducts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: productsControllerGetFeaturedProductsQueryKey(options),
  });
};

export const productsControllerGetProductBySlugQueryKey = (
  options: OptionsLegacyParser<ProductsControllerGetProductBySlugData>,
) => [createQueryKey('productsControllerGetProductBySlug', options)];

export const productsControllerGetProductBySlugOptions = (
  options: OptionsLegacyParser<ProductsControllerGetProductBySlugData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await productsControllerGetProductBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: productsControllerGetProductBySlugQueryKey(options),
  });
};

export const productsControllerGetProductsByFilterQueryKey = (
  options: OptionsLegacyParser<ProductsControllerGetProductsByFilterData>,
) => [createQueryKey('productsControllerGetProductsByFilter', options)];

export const productsControllerGetProductsByFilterOptions = (
  options: OptionsLegacyParser<ProductsControllerGetProductsByFilterData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await productsControllerGetProductsByFilter({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: productsControllerGetProductsByFilterQueryKey(options),
  });
};

export const cartsControllerGetCartQueryKey = (
  options?: OptionsLegacyParser,
) => [createQueryKey('cartsControllerGetCart', options)];

export const cartsControllerGetCartOptions = (
  options?: OptionsLegacyParser,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cartsControllerGetCart({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cartsControllerGetCartQueryKey(options),
  });
};

export const cartsControllerAddToCartQueryKey = (
  options: OptionsLegacyParser<CartsControllerAddToCartData>,
) => [createQueryKey('cartsControllerAddToCart', options)];

export const cartsControllerAddToCartOptions = (
  options: OptionsLegacyParser<CartsControllerAddToCartData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cartsControllerAddToCart({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cartsControllerAddToCartQueryKey(options),
  });
};

export const cartsControllerAddToCartMutation = (
  options?: Partial<OptionsLegacyParser<CartsControllerAddToCartData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CartsControllerAddToCartResponse,
    CartsControllerAddToCartError,
    OptionsLegacyParser<CartsControllerAddToCartData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await cartsControllerAddToCart({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cartsControllerRemoveFromCartMutation = (
  options?: Partial<OptionsLegacyParser<CartsControllerRemoveFromCartData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CartsControllerRemoveFromCartResponse,
    CartsControllerRemoveFromCartError,
    OptionsLegacyParser<CartsControllerRemoveFromCartData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await cartsControllerRemoveFromCart({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const ordersControllerGetOrdersQueryKey = (
  options?: OptionsLegacyParser,
) => [createQueryKey('ordersControllerGetOrders', options)];

export const ordersControllerGetOrdersOptions = (
  options?: OptionsLegacyParser,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ordersControllerGetOrders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: ordersControllerGetOrdersQueryKey(options),
  });
};

export const ordersControllerCreateOrderQueryKey = (
  options?: OptionsLegacyParser,
) => [createQueryKey('ordersControllerCreateOrder', options)];

export const ordersControllerCreateOrderOptions = (
  options?: OptionsLegacyParser,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ordersControllerCreateOrder({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: ordersControllerCreateOrderQueryKey(options),
  });
};

export const ordersControllerCreateOrderMutation = (
  options?: Partial<OptionsLegacyParser>,
) => {
  const mutationOptions: UseMutationOptions<
    OrdersControllerCreateOrderResponse,
    OrdersControllerCreateOrderError,
    OptionsLegacyParser
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ordersControllerCreateOrder({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const ordersControllerGetOrderIntentQueryKey = (
  options: OptionsLegacyParser<OrdersControllerGetOrderIntentData>,
) => [createQueryKey('ordersControllerGetOrderIntent', options)];

export const ordersControllerGetOrderIntentOptions = (
  options: OptionsLegacyParser<OrdersControllerGetOrderIntentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ordersControllerGetOrderIntent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: ordersControllerGetOrderIntentQueryKey(options),
  });
};

export const ordersControllerGetOrderQueryKey = (
  options: OptionsLegacyParser<OrdersControllerGetOrderData>,
) => [createQueryKey('ordersControllerGetOrder', options)];

export const ordersControllerGetOrderOptions = (
  options: OptionsLegacyParser<OrdersControllerGetOrderData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ordersControllerGetOrder({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: ordersControllerGetOrderQueryKey(options),
  });
};

export const ordersControllerCancelOrderMutation = (
  options?: Partial<OptionsLegacyParser<OrdersControllerCancelOrderData>>,
) => {
  const mutationOptions: UseMutationOptions<
    OrdersControllerCancelOrderResponse,
    OrdersControllerCancelOrderError,
    OptionsLegacyParser<OrdersControllerCancelOrderData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ordersControllerCancelOrder({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
