// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from '@hey-api/client-fetch';
import type {
  AuthControllerMeError,
  AuthControllerMeResponse,
  AuthControllerSigninData,
  AuthControllerSigninError,
  AuthControllerSigninResponse,
  AuthControllerSignupData,
  AuthControllerSignupError,
  AuthControllerSignupResponse,
  CartsControllerAddToCartData,
  CartsControllerAddToCartError,
  CartsControllerAddToCartResponse,
  CartsControllerGetCartError,
  CartsControllerGetCartQuantityError,
  CartsControllerGetCartQuantityResponse,
  CartsControllerGetCartResponse,
  CartsControllerRemoveProductData,
  CartsControllerRemoveProductError,
  CartsControllerRemoveProductResponse,
  CartsControllerUpdateProductQuantityData,
  CartsControllerUpdateProductQuantityError,
  CartsControllerUpdateProductQuantityResponse,
  ProductsControllerGetFeaturedProductsData,
  ProductsControllerGetFeaturedProductsError,
  ProductsControllerGetFeaturedProductsResponse,
  ProductsControllerGetProductByIdData,
  ProductsControllerGetProductByIdError,
  ProductsControllerGetProductByIdResponse,
  ProductsControllerGetProductsByFilterData,
  ProductsControllerGetProductsByFilterError,
  ProductsControllerGetProductsByFilterResponse,
} from './types.gen';

export const client = createClient(createConfig());

export const authControllerSignup = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthControllerSignupData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthControllerSignupResponse,
    AuthControllerSignupError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/signup',
  });
};

export const authControllerSignin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthControllerSigninData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthControllerSigninResponse,
    AuthControllerSigninError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/signin',
  });
};

export const authControllerMe = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuthControllerMeResponse,
    AuthControllerMeError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/me',
  });
};

export const productsControllerGetFeaturedProducts = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ProductsControllerGetFeaturedProductsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetFeaturedProductsResponse,
    ProductsControllerGetFeaturedProductsError,
    ThrowOnError
  >({
    ...options,
    url: '/products/featured',
  });
};

export const productsControllerGetProductById = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ProductsControllerGetProductByIdData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductByIdResponse,
    ProductsControllerGetProductByIdError,
    ThrowOnError
  >({
    ...options,
    url: '/products/{id}',
  });
};

export const productsControllerGetProductsByFilter = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ProductsControllerGetProductsByFilterData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductsByFilterResponse,
    ProductsControllerGetProductsByFilterError,
    ThrowOnError
  >({
    ...options,
    url: '/products',
  });
};

export const cartsControllerGetCartQuantity = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CartsControllerGetCartQuantityResponse,
    CartsControllerGetCartQuantityError,
    ThrowOnError
  >({
    ...options,
    url: '/cart/quantity',
  });
};

export const cartsControllerGetCart = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CartsControllerGetCartResponse,
    CartsControllerGetCartError,
    ThrowOnError
  >({
    ...options,
    url: '/cart',
  });
};

export const cartsControllerAddToCart = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CartsControllerAddToCartData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CartsControllerAddToCartResponse,
    CartsControllerAddToCartError,
    ThrowOnError
  >({
    ...options,
    url: '/cart',
  });
};

export const cartsControllerUpdateProductQuantity = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    CartsControllerUpdateProductQuantityData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    CartsControllerUpdateProductQuantityResponse,
    CartsControllerUpdateProductQuantityError,
    ThrowOnError
  >({
    ...options,
    url: '/cart',
  });
};

export const cartsControllerRemoveProduct = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<CartsControllerRemoveProductData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    CartsControllerRemoveProductResponse,
    CartsControllerRemoveProductError,
    ThrowOnError
  >({
    ...options,
    url: '/cart',
  });
};
