// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from '@hey-api/client-fetch';
import type {
  AuthControllerMeData,
  AuthControllerMeResponse,
  AuthControllerSigninData,
  AuthControllerSigninResponse,
  AuthControllerSignupData,
  AuthControllerSignupResponse,
  ProductsControllerGetProductByIdData,
  ProductsControllerGetProductByIdResponse,
  ProductsControllerGetProductsByFilterData,
  ProductsControllerGetProductsByFilterResponse,
} from './types.gen';

export const client = createClient(createConfig());

export const authControllerSignup = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSignupData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthControllerSignupResponse,
    unknown,
    ThrowOnError
  >({
    url: '/auth/signup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const authControllerSignin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSigninData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthControllerSigninResponse,
    unknown,
    ThrowOnError
  >({
    url: '/auth/signin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const authControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuthControllerMeResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/auth/me',
    ...options,
  });
};

export const productsControllerGetProductById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerGetProductByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductByIdResponse,
    unknown,
    ThrowOnError
  >({
    url: '/products/{id}',
    ...options,
  });
};

export const productsControllerGetProductsByFilter = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerGetProductsByFilterData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProductsControllerGetProductsByFilterResponse,
    unknown,
    ThrowOnError
  >({
    url: '/products',
    ...options,
  });
};
