// This file is auto-generated by @hey-api/openapi-ts

export type AddToCartRequestDto = {
  quantity: number;
};

export type BrandDto = {
  id: number;
  name: string;
};

export type CartItemResponseDto = {
  productId: number;
  price: number;
  quantity: number;
  product: ProductResponseDto;
};

export type CartResponseDto = {
  totalPrice: number;
  totalQuantity: number;
  items: Array<CartItemResponseDto>;
};

export type CategoryDto = {
  id: number;
  name: string;
};

export type GetIntentResponseDto = {
  amount: number;
  status: string;
  currency: string;
  clientSecret: string;
};

export type OrderItemResponseDto = {
  productId: number;
  quantity: number;
  price: number;
};

export type OrderProductsItemResponseDto = {
  productId: number;
  quantity: number;
  price: number;
  product: ProductResponseDto;
};

export type OrderProductsResponseDto = {
  id: number;
  userId: number;
  createdAt: Date;
  status: string;
  intentId: string;
  items: Array<OrderProductsItemResponseDto>;
};

export type OrderResponseDto = {
  id: number;
  userId: number;
  createdAt: Date;
  status: string;
  intentId: string;
  items: Array<OrderItemResponseDto>;
};

export type PaginationRequestDto = {
  page: number;
  limit: number;
};

export type PaginationResponseDto = {
  page: number;
  limit: number;
  totalCount: number;
};

export type ProductResponseDto = {
  id: number;
  amount: number;
  image: string;
  price: number;
  title: string;
  description: string;
  rating?: number | null;
  createdAt: Date;
  brand: BrandDto;
  category: CategoryDto;
};

export type ProductsByFilterResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
  brand: BrandDto;
  category: CategoryDto;
};

export type ProductsResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
};

export type RequestSigninDto = {
  email: string;
  password: string;
};

export type RequestSignupDto = {
  name: string;
  email: string;
  password: string;
};

export type ResponseAuthorizedUserDto = {
  id: number;
  name: string;
  email: string;
};

export type ResponseLoggedInDto = {
  user: ResponseAuthorizedUserDto;
  accessToken: string;
};

export type AuthControllerSignupData = {
  body: RequestSignupDto;
};

export type AuthControllerSignupResponse = ResponseLoggedInDto;

export type AuthControllerSignupError = unknown;

export type AuthControllerSigninData = {
  body: RequestSigninDto;
};

export type AuthControllerSigninResponse = ResponseLoggedInDto;

export type AuthControllerSigninError = unknown;

export type AuthControllerMeResponse = ResponseAuthorizedUserDto;

export type AuthControllerMeError = unknown;

export type ProductsControllerGetFeaturedProductsData = {
  query: {
    pagination: PaginationRequestDto;
  };
};

export type ProductsControllerGetFeaturedProductsResponse = ProductsResponseDto;

export type ProductsControllerGetFeaturedProductsError = unknown;

export type ProductsControllerGetProductByIdData = {
  path: {
    id: number;
  };
};

export type ProductsControllerGetProductByIdResponse = ProductResponseDto;

export type ProductsControllerGetProductByIdError = unknown;

export type ProductsControllerGetProductsByFilterData = {
  query: {
    brandId?: number;
    categoryId?: number;
    pagination: PaginationRequestDto;
  };
};

export type ProductsControllerGetProductsByFilterResponse =
  ProductsByFilterResponseDto;

export type ProductsControllerGetProductsByFilterError = unknown;

export type CartsControllerGetCartResponse = CartResponseDto;

export type CartsControllerGetCartError = unknown;

export type CartsControllerAddToCartData = {
  body: AddToCartRequestDto;
  path: {
    productId: number;
  };
};

export type CartsControllerAddToCartResponse = CartResponseDto;

export type CartsControllerAddToCartError = unknown;

export type CartsControllerRemoveFromCartData = {
  path: {
    productId: number;
  };
};

export type CartsControllerRemoveFromCartResponse = CartResponseDto;

export type CartsControllerRemoveFromCartError = unknown;

export type OrdersControllerGetOrdersResponse = Array<OrderResponseDto>;

export type OrdersControllerGetOrdersError = unknown;

export type OrdersControllerAddOrderResponse = OrderResponseDto;

export type OrdersControllerAddOrderError = unknown;

export type OrdersControllerGetOrderData = {
  path: {
    orderId: number;
  };
};

export type OrdersControllerGetOrderResponse = OrderProductsResponseDto;

export type OrdersControllerGetOrderError = unknown;

export type PaymentsControllerGetIntentData = {
  path: {
    intentId: string;
  };
};

export type PaymentsControllerGetIntentResponse = GetIntentResponseDto;

export type PaymentsControllerGetIntentError = unknown;

export type ProductsControllerGetFeaturedProductsResponseTransformer = (
  data: any,
) => Promise<ProductsControllerGetFeaturedProductsResponse>;

export type ProductsResponseDtoModelResponseTransformer = (
  data: any,
) => ProductsResponseDto;

export type ProductResponseDtoModelResponseTransformer = (
  data: any,
) => ProductResponseDto;

export const ProductResponseDtoModelResponseTransformer: ProductResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    return data;
  };

export const ProductsResponseDtoModelResponseTransformer: ProductsResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.products)) {
      data.products.forEach(ProductResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const ProductsControllerGetFeaturedProductsResponseTransformer: ProductsControllerGetFeaturedProductsResponseTransformer =
  async (data) => {
    ProductsResponseDtoModelResponseTransformer(data);
    return data;
  };

export type ProductsControllerGetProductByIdResponseTransformer = (
  data: any,
) => Promise<ProductsControllerGetProductByIdResponse>;

export const ProductsControllerGetProductByIdResponseTransformer: ProductsControllerGetProductByIdResponseTransformer =
  async (data) => {
    ProductResponseDtoModelResponseTransformer(data);
    return data;
  };

export type ProductsControllerGetProductsByFilterResponseTransformer = (
  data: any,
) => Promise<ProductsControllerGetProductsByFilterResponse>;

export type ProductsByFilterResponseDtoModelResponseTransformer = (
  data: any,
) => ProductsByFilterResponseDto;

export const ProductsByFilterResponseDtoModelResponseTransformer: ProductsByFilterResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.products)) {
      data.products.forEach(ProductResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const ProductsControllerGetProductsByFilterResponseTransformer: ProductsControllerGetProductsByFilterResponseTransformer =
  async (data) => {
    ProductsByFilterResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerGetCartResponseTransformer = (
  data: any,
) => Promise<CartsControllerGetCartResponse>;

export type CartResponseDtoModelResponseTransformer = (
  data: any,
) => CartResponseDto;

export type CartItemResponseDtoModelResponseTransformer = (
  data: any,
) => CartItemResponseDto;

export const CartItemResponseDtoModelResponseTransformer: CartItemResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.product) {
      ProductResponseDtoModelResponseTransformer(data.product);
    }
    return data;
  };

export const CartResponseDtoModelResponseTransformer: CartResponseDtoModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.items)) {
      data.items.forEach(CartItemResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const CartsControllerGetCartResponseTransformer: CartsControllerGetCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerAddToCartResponseTransformer = (
  data: any,
) => Promise<CartsControllerAddToCartResponse>;

export const CartsControllerAddToCartResponseTransformer: CartsControllerAddToCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type CartsControllerRemoveFromCartResponseTransformer = (
  data: any,
) => Promise<CartsControllerRemoveFromCartResponse>;

export const CartsControllerRemoveFromCartResponseTransformer: CartsControllerRemoveFromCartResponseTransformer =
  async (data) => {
    CartResponseDtoModelResponseTransformer(data);
    return data;
  };

export type OrdersControllerGetOrdersResponseTransformer = (
  data: any,
) => Promise<OrdersControllerGetOrdersResponse>;

export type OrderResponseDtoModelResponseTransformer = (
  data: any,
) => OrderResponseDto;

export const OrderResponseDtoModelResponseTransformer: OrderResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    return data;
  };

export const OrdersControllerGetOrdersResponseTransformer: OrdersControllerGetOrdersResponseTransformer =
  async (data) => {
    if (Array.isArray(data)) {
      data.forEach(OrderResponseDtoModelResponseTransformer);
    }
    return data;
  };

export type OrdersControllerAddOrderResponseTransformer = (
  data: any,
) => Promise<OrdersControllerAddOrderResponse>;

export const OrdersControllerAddOrderResponseTransformer: OrdersControllerAddOrderResponseTransformer =
  async (data) => {
    OrderResponseDtoModelResponseTransformer(data);
    return data;
  };

export type OrdersControllerGetOrderResponseTransformer = (
  data: any,
) => Promise<OrdersControllerGetOrderResponse>;

export type OrderProductsResponseDtoModelResponseTransformer = (
  data: any,
) => OrderProductsResponseDto;

export type OrderProductsItemResponseDtoModelResponseTransformer = (
  data: any,
) => OrderProductsItemResponseDto;

export const OrderProductsItemResponseDtoModelResponseTransformer: OrderProductsItemResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.product) {
      ProductResponseDtoModelResponseTransformer(data.product);
    }
    return data;
  };

export const OrderProductsResponseDtoModelResponseTransformer: OrderProductsResponseDtoModelResponseTransformer =
  (data) => {
    if (data?.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    if (Array.isArray(data?.items)) {
      data.items.forEach(OrderProductsItemResponseDtoModelResponseTransformer);
    }
    return data;
  };

export const OrdersControllerGetOrderResponseTransformer: OrdersControllerGetOrderResponseTransformer =
  async (data) => {
    OrderProductsResponseDtoModelResponseTransformer(data);
    return data;
  };
