// This file is auto-generated by @hey-api/openapi-ts

export type RequestSignupDto = {
  name: string;
  email: string;
  password: string;
};

export type ResponseAuthorizedUserDto = {
  id: number;
  name: string;
  email: string;
};

export type ResponseLoggedInDto = {
  user: ResponseAuthorizedUserDto;
  accessToken: string;
};

export type RequestSigninDto = {
  email: string;
  password: string;
};

export type PaginationRequestDto = {
  page: number;
  limit: number;
};

export type BrandDto = {
  id: number;
  name: string;
};

export type CategoryDto = {
  id: number;
  name: string;
};

export type ProductResponseDto = {
  id: number;
  amount: number;
  currency: string;
  image: string;
  price: number;
  title: string;
  description: string;
  rating?: number | null;
  createdAt: string;
  brand: BrandDto;
  category: CategoryDto;
};

export type PaginationResponseDto = {
  page: number;
  limit: number;
  totalCount: number;
};

export type ProductsResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
};

export type ProductsByFilterResponseDto = {
  products: Array<ProductResponseDto>;
  pagination: PaginationResponseDto;
  brand: BrandDto;
  category: CategoryDto;
};

export type AuthControllerSignupData = {
  body: RequestSignupDto;
  path?: never;
  query?: never;
  url: '/auth/signup';
};

export type AuthControllerSignupResponses = {
  200: ResponseLoggedInDto;
};

export type AuthControllerSignupResponse =
  AuthControllerSignupResponses[keyof AuthControllerSignupResponses];

export type AuthControllerSigninData = {
  body: RequestSigninDto;
  path?: never;
  query?: never;
  url: '/auth/signin';
};

export type AuthControllerSigninResponses = {
  200: ResponseLoggedInDto;
};

export type AuthControllerSigninResponse =
  AuthControllerSigninResponses[keyof AuthControllerSigninResponses];

export type AuthControllerMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type AuthControllerMeResponses = {
  200: ResponseAuthorizedUserDto;
};

export type AuthControllerMeResponse =
  AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type ProductsControllerGetFeaturedProductsData = {
  body?: never;
  path?: never;
  query: {
    pagination: PaginationRequestDto;
  };
  url: '/products/featured';
};

export type ProductsControllerGetFeaturedProductsResponses = {
  200: ProductsResponseDto;
};

export type ProductsControllerGetFeaturedProductsResponse =
  ProductsControllerGetFeaturedProductsResponses[keyof ProductsControllerGetFeaturedProductsResponses];

export type ProductsControllerGetProductByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsControllerGetProductByIdResponses = {
  200: ProductResponseDto;
};

export type ProductsControllerGetProductByIdResponse =
  ProductsControllerGetProductByIdResponses[keyof ProductsControllerGetProductByIdResponses];

export type ProductsControllerGetProductsByFilterData = {
  body?: never;
  path?: never;
  query: {
    brandId?: number;
    categoryId?: number;
    pagination: PaginationRequestDto;
  };
  url: '/products';
};

export type ProductsControllerGetProductsByFilterResponses = {
  200: ProductsByFilterResponseDto;
};

export type ProductsControllerGetProductsByFilterResponse =
  ProductsControllerGetProductsByFilterResponses[keyof ProductsControllerGetProductsByFilterResponses];
