// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import {
  queryOptions,
  type DefaultError,
  type UseMutationOptions,
} from '@tanstack/react-query';
import {
  authControllerMe,
  authControllerSignin,
  authControllerSignup,
  client,
} from '../sdk.gen';
import type {
  AuthControllerMeData,
  AuthControllerSigninData,
  AuthControllerSigninResponse,
  AuthControllerSignupData,
  AuthControllerSignupResponse,
} from '../types.gen';

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const authControllerSignupQueryKey = (
  options: Options<AuthControllerSignupData>,
) => [createQueryKey('authControllerSignup', options)];

export const authControllerSignupOptions = (
  options: Options<AuthControllerSignupData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerSignup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerSignupQueryKey(options),
  });
};

export const authControllerSignupMutation = (
  options?: Partial<Options<AuthControllerSignupData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AuthControllerSignupResponse,
    DefaultError,
    Options<AuthControllerSignupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await authControllerSignup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authControllerSigninQueryKey = (
  options: Options<AuthControllerSigninData>,
) => [createQueryKey('authControllerSignin', options)];

export const authControllerSigninOptions = (
  options: Options<AuthControllerSigninData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerSignin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerSigninQueryKey(options),
  });
};

export const authControllerSigninMutation = (
  options?: Partial<Options<AuthControllerSigninData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AuthControllerSigninResponse,
    DefaultError,
    Options<AuthControllerSigninData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await authControllerSignin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authControllerMeQueryKey = (
  options?: Options<AuthControllerMeData>,
) => [createQueryKey('authControllerMe', options)];

export const authControllerMeOptions = (
  options?: Options<AuthControllerMeData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authControllerMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authControllerMeQueryKey(options),
  });
};
